/*
 * VM Auto Scaling service (CloudAPI)
 *
 * VM Auto Scaling service enables IONOS clients to horizontally scale the number of VM instances, based on configured rules. Use Auto Scaling to ensure you will have a sufficient number of instances to handle your application loads at all times.  Create an Auto Scaling group that contains the server instances; Auto Scaling service will ensure that the number of instances in the group is always within these limits.  When target replica count is specified, Auto Scaling will maintain the set number on instances.  When scaling policies are specified, Auto Scaling will create or delete instances based on the demands of your applications. For each policy, specified scale-in and scale-out actions are performed whenever the corresponding thresholds are met.
 *
 * API version: 1.0
 * Contact: support@cloud.ionos.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ionoscloud_vm_autoscaling

import (
	"encoding/json"
	"fmt"
)

// BusType The bus type of the volume. Default is VIRTIO. Also supported: IDE.
type BusType string

// List of BusType
const (
	VIRTIO BusType = "VIRTIO"
	IDE    BusType = "IDE"
)

func (v *BusType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := BusType(value)
	for _, existing := range []BusType{"VIRTIO", "IDE"} {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid BusType", value)
}

// Ptr returns reference to BusType value
func (v BusType) Ptr() *BusType {
	return &v
}

type NullableBusType struct {
	value *BusType
	isSet bool
}

func (v NullableBusType) Get() *BusType {
	return v.value
}

func (v *NullableBusType) Set(val *BusType) {
	v.value = val
	v.isSet = true
}

func (v NullableBusType) IsSet() bool {
	return v.isSet
}

func (v *NullableBusType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBusType(val *BusType) *NullableBusType {
	return &NullableBusType{value: val, isSet: true}
}

func (v NullableBusType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBusType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
