/*
 * VM Auto Scaling service (CloudAPI)
 *
 * VM Auto Scaling service enables IONOS clients to horizontally scale the number of VM instances, based on configured rules. Use Auto Scaling to ensure you will have a sufficient number of instances to handle your application loads at all times.  Create an Auto Scaling group that contains the server instances; Auto Scaling service will ensure that the number of instances in the group is always within these limits.  When target replica count is specified, Auto Scaling will maintain the set number on instances.  When scaling policies are specified, Auto Scaling will create or delete instances based on the demands of your applications. For each policy, specified scale-in and scale-out actions are performed whenever the corresponding thresholds are met.
 *
 * API version: 1.0
 * Contact: support@cloud.ionos.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ionoscloud_vm_autoscaling

import (
	"encoding/json"
)

// GroupCollectionAllOf struct for GroupCollectionAllOf
type GroupCollectionAllOf struct {
	// URL to the object representation (absolute path)
	Href *string `json:"href,omitempty"`
	// The resource's unique identifier
	Id    *string  `json:"id,omitempty"`
	Items *[]Group `json:"items,omitempty"`
}

// NewGroupCollectionAllOf instantiates a new GroupCollectionAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGroupCollectionAllOf() *GroupCollectionAllOf {
	this := GroupCollectionAllOf{}

	return &this
}

// NewGroupCollectionAllOfWithDefaults instantiates a new GroupCollectionAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGroupCollectionAllOfWithDefaults() *GroupCollectionAllOf {
	this := GroupCollectionAllOf{}
	return &this
}

// GetHref returns the Href field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GroupCollectionAllOf) GetHref() *string {
	if o == nil {
		return nil
	}

	return o.Href

}

// GetHrefOk returns a tuple with the Href field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GroupCollectionAllOf) GetHrefOk() (*string, bool) {
	if o == nil {
		return nil, false
	}

	return o.Href, true
}

// SetHref sets field value
func (o *GroupCollectionAllOf) SetHref(v string) {

	o.Href = &v

}

// HasHref returns a boolean if a field has been set.
func (o *GroupCollectionAllOf) HasHref() bool {
	if o != nil && o.Href != nil {
		return true
	}

	return false
}

// GetId returns the Id field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GroupCollectionAllOf) GetId() *string {
	if o == nil {
		return nil
	}

	return o.Id

}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GroupCollectionAllOf) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}

	return o.Id, true
}

// SetId sets field value
func (o *GroupCollectionAllOf) SetId(v string) {

	o.Id = &v

}

// HasId returns a boolean if a field has been set.
func (o *GroupCollectionAllOf) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// GetItems returns the Items field value
// If the value is explicit nil, the zero value for []Group will be returned
func (o *GroupCollectionAllOf) GetItems() *[]Group {
	if o == nil {
		return nil
	}

	return o.Items

}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GroupCollectionAllOf) GetItemsOk() (*[]Group, bool) {
	if o == nil {
		return nil, false
	}

	return o.Items, true
}

// SetItems sets field value
func (o *GroupCollectionAllOf) SetItems(v []Group) {

	o.Items = &v

}

// HasItems returns a boolean if a field has been set.
func (o *GroupCollectionAllOf) HasItems() bool {
	if o != nil && o.Items != nil {
		return true
	}

	return false
}

func (o GroupCollectionAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Href != nil {
		toSerialize["href"] = o.Href
	}

	if o.Id != nil {
		toSerialize["id"] = o.Id
	}

	if o.Items != nil {
		toSerialize["items"] = o.Items
	}

	return json.Marshal(toSerialize)
}

type NullableGroupCollectionAllOf struct {
	value *GroupCollectionAllOf
	isSet bool
}

func (v NullableGroupCollectionAllOf) Get() *GroupCollectionAllOf {
	return v.value
}

func (v *NullableGroupCollectionAllOf) Set(val *GroupCollectionAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableGroupCollectionAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableGroupCollectionAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGroupCollectionAllOf(val *GroupCollectionAllOf) *NullableGroupCollectionAllOf {
	return &NullableGroupCollectionAllOf{value: val, isSet: true}
}

func (v NullableGroupCollectionAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGroupCollectionAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
